### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by ryanallandorn** [flavea/ci4-vue#5]
First off, great work!

I was able to set up everything correctly, but was running into issue with respect to CORS on the dev mode. Specifically, I keep getting the following error:

> Access to XMLHttpRequest at 'http://example.com/public/api/book/get' from origin 'http://example.com:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I've read quite a few threads and Mozilla's article on CORS ...I understand

- What CORS is,
- That the CORS issues is likely due to my PHP app running on port 80 and my Vue/Node/Webpack App Running on Port 8080 in dev mode.

What I don't understand where I need to resolve it...Apache, my PHP App, Vue, Webpack? (my suspicion is WebPack / Node).

My question ...how do I resolve this CORS issue for my dev mode?

Huge thanks in advance!

**Comment by flavea** [comment]
Hello, sorry for the late answer! Yes, we need to configure the server for CORS, but I think the quickest workaround for now will be by setting headers on the API controller. Can you try adding the following code under the get function on [this file](https://github.com/flavea/ci4-vue/blob/master/app/Controllers/Api/Book.php)? Sorry, can't test it out by myself rn!

`header( 'Access-Control-Allow-Credentials: true' );
header( 'Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS' );
header( 'Access-Control-Allow-Headers: ACCEPT, ORIGIN, X-REQUESTED-WITH, CONTENT-TYPE, AUTHORIZATION' );
header( 'Access-Control-Max-Age: 86400' );`

**Comment by ryanallandorn** [comment]
Thanks for the reply! I had tried adding headers to that controller, but tried again as you indicated.

After a bit of fiddling around, this worked for me:

```
        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
        header("Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding");

        $model = new BookModel();
        return $this->respond(['books' => $model->getAllBooks()]);
```
